name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Tu installe l'outils mais tu le run pas ?
      - name: Install cargo-audit
        if: startsWith(github.event.pull_request.base.ref, 'release/')
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi
      - name: Build project
        shell: bash
        run: make build

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Caching ?
      - name: Run checks
        shell: bash
        run: make check

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        shell: bash
        run: make test
      - name: Run integration tests
        if: startsWith(github.event.pull_request.base.ref, 'release/')
        shell: bash
        run: |
          cargo run --features testing &
          until nc -z localhost 9345; do sleep 1; done  # Boucle infinie si le serveur démarre pas
          python3 tests/gameplay.test.py
      # Donc tu fais un test + un heavy test, rigolo (bon ça va c'est pas horrible)
      - name: Run heavy-testing
        if: startsWith(github.event.pull_request.base.ref, 'release/')
        shell: bash
        run: cargo test --features heavy-testing
  audit:
    needs: build
    if: startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-audit if missing
        run: |
          if ! command -v cargo-audit &> /dev/null; then
            cargo install cargo-audit
          fi
      - name: Run cargo audit
        run: cargo audit
  deps:
    needs: build
    if: startsWith(github.event.pull_request.base.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install toml
        run: pip install toml
      - name: Check-deps
        shell: bash
        run: python3 .github/tototutu.py  # Bien suuuuuur

  manual:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install typst
        run: |
          # Sinon cargo install
          # Avec du cache ça serait encore mieux
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin  # Pas de sudo dans un workflow, on est déjà root

      - name: Build manual
        shell: bash
        run: make manual

  quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Caching ?

      - name: Format check
        run: cargo fmt --check

      - name: Clippy lints
        run: cargo clippy

  build-release:
    needs: [build, check, tests, deps, manual, quality]
    if: startsWith(github.event.pull_request.base.ref, 'release/')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build release
        shell: bash
        run: make release
