name: Code Quality Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check compilation
        run: cargo check

      - name: Format check
        run: cargo fmt --check

      - name: Clippy lints
        run: cargo clippy --all-targets --all-features -- -D warnings
