name: Comment on new PR

on:
  pull_request:
    types: [opened]

jobs:
  comment-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Post comment using API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d '{"body": "Thank you for your pull request! We will review it shortly. Make sure you have followed the contribution guidelines and that your code passes all tests."}'
