name: Auto Release

on:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last tag
        id: last_tag
        run: |
          git fetch --tags
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "last_tag=$last_tag" >> $GITHUB_OUTPUT

      - name: Generate changelog from conventional commits
        id: changelog
        run: |
          since="${{ steps.last_tag.outputs.last_tag }}"
          if [ -z "$since" ]; then
            range=""
          else
            range="$since..HEAD"
          fi

          echo "features=" >> $GITHUB_OUTPUT
          echo "bugfixes=" >> $GITHUB_OUTPUT
          echo "others=" >> $GITHUB_OUTPUT

          commits=$(git log $range --pretty=format:"%s %h")

          features=""
          bugfixes=""
          others=""

          while IFS= read -r line; do
            if [[ "$line" =~ ^feat ]]; then
              features+="* $line"$'\n'
            elif [[ "$line" =~ ^fix ]]; then
              bugfixes+="* $line"$'\n'
            else
              others+="* $line"$'\n'
            fi
          done <<< "$commits"

          echo "features<<EOF" >> $GITHUB_OUTPUT
          echo "$features" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "bugfixes<<EOF" >> $GITHUB_OUTPUT
          echo "$bugfixes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "others<<EOF" >> $GITHUB_OUTPUT
          echo "$others" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build release artifacts
        run: |
          make release
          mkdir -p release-artifacts
          cp target/release/simeis-server release-artifacts/
          cp doc/manual.pdf release-artifacts/ || true

      - name: Create GitHub Release
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "release-${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          body: |
            ## Changelog

            ### Features
            ${{ steps.changelog.outputs.features }}

            ### Bugfixes
            ${{ steps.changelog.outputs.bugfixes }}

            ### Other
            ${{ steps.changelog.outputs.others }}

            [Workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          files: |
            release-artifacts/*
          clear_attachments: true
