name: Auto Release

on:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version tag from ref name
        id: extract_tag
        run: |
          full_ref="${GITHUB_REF_NAME}"
          version="${full_ref##*/}"
          echo "version_tag=$version" >> $GITHUB_OUTPUT

      - name: Generate changelog from PR titles
        id: changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch --tags

          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          commit_range="${last_tag}..HEAD"

          prs=$(git log --merges --pretty=format:"%s" $commit_range | grep -Eo '#[0-9]+' | sed 's/#//' | sort -u)

          features=""
          bugfixes=""
          others=""

          for pr in $prs; do
            data=$(gh pr view $pr --json headRefName,title,url -q '.')
            branch=$(echo "$data" | jq -r '.headRefName')
            title=$(echo "$data" | jq -r '.title')
            url=$(echo "$data" | jq -r '.url')
            entry="* [$title]($url)"

            if [[ "$branch" == feature/* ]]; then
              features+="$entry"$'\n'
            elif [[ "$branch" == bug/* ]]; then
              bugfixes+="$entry"$'\n'
            else
              others+="$entry"$'\n'
            fi
          done

          echo "features<<EOF" >> $GITHUB_OUTPUT
          echo "${features:-_None_}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "bugfixes<<EOF" >> $GITHUB_OUTPUT
          echo "${bugfixes:-_None_}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "others<<EOF" >> $GITHUB_OUTPUT
          echo "${others:-_None_}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build release artifacts
        run: |
          make release
          mkdir -p release-artifacts
          cp target/release/simeis-server release-artifacts/
          cp doc/manual.pdf release-artifacts/ || true

      - name: Create GitHub Release
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.extract_tag.outputs.version_tag }}"
          name: "Release ${{ steps.extract_tag.outputs.version_tag }}"
          body: |
            ## Changelog

            ### Features
            ${{ steps.changelog.outputs.features }}

            ### Bugfixes
            ${{ steps.changelog.outputs.bugfixes }}

            ### Other
            ${{ steps.changelog.outputs.others }}

            [Workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          files: |
            release-artifacts/*
          clear_attachments: true
