name: Auto Update Rust Dependencies

on:
  schedule:
    - cron: '*/2 * * * *'  # Every monday at 07:00 UTC
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update dependencies
        run: cargo update

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(deps): upgrade Rust dependencies"
          branch: bot/dependency-update
          file_pattern: "Cargo.toml Cargo.lock"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/dependency-update
          title: "chore(deps): update Rust dependencies"
          body: |
            📦 Cette PR a été générée automatiquement pour mettre à jour les dépendances Rust via `cargo update`.
          labels: bot/update
